-- MySQL Script generated by MySQL Workbench
-- Tue Dec 19 01:41:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`countries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`countries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(56) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `CountryID_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `country_name_UNIQUE` (`country_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sport_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sport_types` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sport_types` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `is_individual` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sports` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sports` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sport_type_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sportTypeID_idx` (`sport_type_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `sport_type_id`
    FOREIGN KEY (`sport_type_id`)
    REFERENCES `mydb`.`sport_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`participants` ;

CREATE TABLE IF NOT EXISTS `mydb`.`participants` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_id` BIGINT UNSIGNED NOT NULL,
  `sport_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  `gender` ENUM("Female", "Male") NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `CountryID_idx` (`country_id` ASC) VISIBLE,
  INDEX `SportID_idx` (`sport_id` ASC) VISIBLE,
  UNIQUE INDEX `ParticipantID_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`countries` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `sport_id`
    FOREIGN KEY (`sport_id`)
    REFERENCES `mydb`.`sports` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venues` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venues` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `address` VARCHAR(100) NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`olympics_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`olympics_types` ;

CREATE TABLE IF NOT EXISTS `mydb`.`olympics_types` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`olympics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`olympics` ;

CREATE TABLE IF NOT EXISTS `mydb`.`olympics` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `olympics_type_id` BIGINT UNSIGNED NOT NULL,
  `country_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `OlympicsTypeID_idx` (`olympics_type_id` ASC) VISIBLE,
  INDEX `CountryID_idx` (`country_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `olympics_type_id`
    FOREIGN KEY (`olympics_type_id`)
    REFERENCES `mydb`.`olympics_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `country_id_ol_fk`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`countries` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`game_types` ;

CREATE TABLE IF NOT EXISTS `mydb`.`game_types` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Like finals, preeliminary etc',
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`teams` ;

CREATE TABLE IF NOT EXISTS `mydb`.`teams` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country_id` BIGINT UNSIGNED NOT NULL,
  `captain_id` BIGINT UNSIGNED NOT NULL,
  `team_name` VARCHAR(20) NOT NULL,
  `squad_size` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `CountryID_idx` (`country_id` ASC) VISIBLE,
  INDEX `CaptainID_idx` (`captain_id` ASC) VISIBLE,
  UNIQUE INDEX `TeamID_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `country_id_teams_fk`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`countries` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `captain_id`
    FOREIGN KEY (`captain_id`)
    REFERENCES `mydb`.`participants` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`games` ;

CREATE TABLE IF NOT EXISTS `mydb`.`games` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `olympics_id` BIGINT UNSIGNED NOT NULL,
  `venue_id` BIGINT UNSIGNED NOT NULL,
  `sport_id` BIGINT UNSIGNED NOT NULL,
  `game_type_id` BIGINT UNSIGNED NOT NULL,
  `winner_id` BIGINT UNSIGNED NULL,
  `winner_team_id` BIGINT UNSIGNED NULL,
  `result` VARCHAR(10) NOT NULL COMMENT 'win / draw / not played / cancelled\n',
  `date_of_game` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `OlympicsID_idx` (`olympics_id` ASC) VISIBLE,
  INDEX `VenueID_idx` (`venue_id` ASC) VISIBLE,
  INDEX `SportID_idx` (`sport_id` ASC) VISIBLE,
  INDEX `typeID_idx` (`game_type_id` ASC) VISIBLE,
  INDEX `WinnerTeamID_idx` (`winner_team_id` ASC) VISIBLE,
  INDEX `WinnerID_idx` (`winner_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `olympics_id`
    FOREIGN KEY (`olympics_id`)
    REFERENCES `mydb`.`olympics` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `venue_id`
    FOREIGN KEY (`venue_id`)
    REFERENCES `mydb`.`venues` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `sport_id_games_fk`
    FOREIGN KEY (`sport_id`)
    REFERENCES `mydb`.`sports` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `type_id`
    FOREIGN KEY (`game_type_id`)
    REFERENCES `mydb`.`game_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `winner_id`
    FOREIGN KEY (`winner_id`)
    REFERENCES `mydb`.`participants` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `winner_team_id`
    FOREIGN KEY (`winner_team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medals` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `medal_name` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team_has_members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`team_has_members` ;

CREATE TABLE IF NOT EXISTS `mydb`.`team_has_members` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `team_id` BIGINT UNSIGNED NOT NULL,
  `member_id` BIGINT UNSIGNED NOT NULL,
  INDEX `TeamID_idx` (`team_id` ASC) VISIBLE,
  INDEX `MemberID_idx` (`member_id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `team_id`, `member_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `member_id`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`participants` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`individual_scores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`individual_scores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`individual_scores` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `participant_id` BIGINT UNSIGNED NOT NULL,
  `game_id` BIGINT UNSIGNED NOT NULL,
  `time` TIME NULL,
  `points` DECIMAL(2) NULL,
  `distance` DECIMAL(2) NULL,
  PRIMARY KEY (`id`),
  INDEX `ParticipantID_idx` (`participant_id` ASC) VISIBLE,
  INDEX `GameID_idx` (`game_id` ASC) VISIBLE,
  UNIQUE INDEX `idIndividualScores_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `participant_id`
    FOREIGN KEY (`participant_id`)
    REFERENCES `mydb`.`participants` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`games` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team_scores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`team_scores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`team_scores` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_id` BIGINT UNSIGNED NOT NULL,
  `team_id` BIGINT UNSIGNED NOT NULL,
  `team_points` DECIMAL(2) NULL,
  `team_time` TIME NULL,
  PRIMARY KEY (`id`),
  INDEX `GameID_idx` (`game_id` ASC) VISIBLE,
  INDEX `TeamID_idx` (`team_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `game_id_ts_fk`
    FOREIGN KEY (`game_id`)
    REFERENCES `mydb`.`games` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `team_id_ts_fk`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`scoreboards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`scoreboards` ;

CREATE TABLE IF NOT EXISTS `mydb`.`scoreboards` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `olympics_id` BIGINT UNSIGNED NOT NULL,
  `sport_id` BIGINT UNSIGNED NOT NULL,
  `participant_id` BIGINT UNSIGNED,
  `team_id` BIGINT UNSIGNED,
  `medal_id` BIGINT UNSIGNED,
  `place` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `OlympicsID_idx` (`olympics_id` ASC) VISIBLE,
  INDEX `SportID_idx` (`sport_id` ASC) VISIBLE,
  INDEX `ParticipantID_idx` (`participant_id` ASC) VISIBLE,
  INDEX `TeamID_idx` (`team_id` ASC) VISIBLE,
  INDEX `MedalID_idx` (`medal_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `olympics_id_sc_fk`
    FOREIGN KEY (`olympics_id`)
    REFERENCES `mydb`.`olympics` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `sport_id_sc_fk`
    FOREIGN KEY (`sport_id`)
    REFERENCES `mydb`.`sports` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `participant_id_sc_fk`
    FOREIGN KEY (`participant_id`)
    REFERENCES `mydb`.`participants` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `team_id_sc_fk`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`teams` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `medal_id`
    FOREIGN KEY (`medal_id`)
    REFERENCES `mydb`.`medals` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
